### PR TITLE
Fix Deprecations for Symfony 4.2

### PR DESCRIPTION
**Pull request by DemigodCode**

### CODE REVIEW

**Comment by NAYZO** [comment]
Thank you for the PR.
Could you git squash yours commits.
Thanks

**Comment by DemigodCode** [comment]
Like that? Never done this before.

**Comment by NAYZO** [comment]
No nott live that, I will do it :)

**Comment by NAYZO** [comment]
Closed in favor of : https://github.com/NAYZO/NzoUrlEncryptorBundle/pull/35

**Pull request closed without merging**
